// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: special-backend.proto

package special_app_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_special_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{0}
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   *string                `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_special_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_special_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{2}
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *GetUserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetIventInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventInfoRequest) Reset() {
	*x = GetIventInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventInfoRequest) ProtoMessage() {}

func (x *GetIventInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIventInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetIventInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventsRequest) Reset() {
	*x = GetIventsRequest{}
	mi := &file_special_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventsRequest) ProtoMessage() {}

func (x *GetIventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventsRequest.ProtoReflect.Descriptor instead.
func (*GetIventsRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{5}
}

type GetIventInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int64                  `protobuf:"varint,6,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats int64                  `protobuf:"varint,7,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	Pictures      []string               `protobuf:"bytes,8,rep,name=pictures,proto3" json:"pictures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventInfoResponse) Reset() {
	*x = GetIventInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventInfoResponse) ProtoMessage() {}

func (x *GetIventInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventInfoResponse.ProtoReflect.Descriptor instead.
func (*GetIventInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{6}
}

func (x *GetIventInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetIventInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetIventInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetIventInfoResponse) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *GetIventInfoResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetIventInfoResponse) GetTotalSeats() int64 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *GetIventInfoResponse) GetOccupiedSeats() int64 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *GetIventInfoResponse) GetPictures() []string {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type IventInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int64                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats int64                  `protobuf:"varint,6,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	Picture       string                 `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IventInfoForList) Reset() {
	*x = IventInfoForList{}
	mi := &file_special_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IventInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IventInfoForList) ProtoMessage() {}

func (x *IventInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IventInfoForList.ProtoReflect.Descriptor instead.
func (*IventInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{7}
}

func (x *IventInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IventInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IventInfoForList) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *IventInfoForList) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *IventInfoForList) GetTotalSeats() int64 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *IventInfoForList) GetOccupiedSeats() int64 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *IventInfoForList) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type GetIventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ivents        []*IventInfoForList    `protobuf:"bytes,1,rep,name=ivents,proto3" json:"ivents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIventsResponse) Reset() {
	*x = GetIventsResponse{}
	mi := &file_special_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIventsResponse) ProtoMessage() {}

func (x *GetIventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIventsResponse.ProtoReflect.Descriptor instead.
func (*GetIventsResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{8}
}

func (x *GetIventsResponse) GetIvents() []*IventInfoForList {
	if x != nil {
		return x.Ivents
	}
	return nil
}

type CreateUserIventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IventId        string                 `protobuf:"bytes,1,opt,name=ivent_id,json=iventId,proto3" json:"ivent_id,omitempty"`
	NumberOfGuests int64                  `protobuf:"varint,2,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserIventRequest) Reset() {
	*x = CreateUserIventRequest{}
	mi := &file_special_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserIventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserIventRequest) ProtoMessage() {}

func (x *CreateUserIventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserIventRequest.ProtoReflect.Descriptor instead.
func (*CreateUserIventRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserIventRequest) GetIventId() string {
	if x != nil {
		return x.IventId
	}
	return ""
}

func (x *CreateUserIventRequest) GetNumberOfGuests() int64 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type GetUserIventInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIventInfoRequest) Reset() {
	*x = GetUserIventInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIventInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIventInfoRequest) ProtoMessage() {}

func (x *GetUserIventInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIventInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserIventInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserIventInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserIventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIventsRequest) Reset() {
	*x = GetUserIventsRequest{}
	mi := &file_special_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIventsRequest) ProtoMessage() {}

func (x *GetUserIventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIventsRequest.ProtoReflect.Descriptor instead.
func (*GetUserIventsRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{11}
}

type UpdateUserIventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumberOfGuests int64                  `protobuf:"varint,2,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserIventRequest) Reset() {
	*x = UpdateUserIventRequest{}
	mi := &file_special_backend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserIventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserIventRequest) ProtoMessage() {}

func (x *UpdateUserIventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserIventRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserIventRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserIventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserIventRequest) GetNumberOfGuests() int64 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type DeleteUserIventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserIventRequest) Reset() {
	*x = DeleteUserIventRequest{}
	mi := &file_special_backend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserIventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserIventRequest) ProtoMessage() {}

func (x *DeleteUserIventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserIventRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserIventRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserIventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserIventInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IventId        string                 `protobuf:"bytes,2,opt,name=ivent_id,json=iventId,proto3" json:"ivent_id,omitempty"`
	NumberOfGuests string                 `protobuf:"bytes,3,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Datetime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Picture        string                 `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserIventInfoResponse) Reset() {
	*x = GetUserIventInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIventInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIventInfoResponse) ProtoMessage() {}

func (x *GetUserIventInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIventInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserIventInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserIventInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserIventInfoResponse) GetIventId() string {
	if x != nil {
		return x.IventId
	}
	return ""
}

func (x *GetUserIventInfoResponse) GetNumberOfGuests() string {
	if x != nil {
		return x.NumberOfGuests
	}
	return ""
}

func (x *GetUserIventInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetUserIventInfoResponse) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *GetUserIventInfoResponse) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type UserIventInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IventId       string                 `protobuf:"bytes,2,opt,name=ivent_id,json=iventId,proto3" json:"ivent_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Picture       string                 `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIventInfoForList) Reset() {
	*x = UserIventInfoForList{}
	mi := &file_special_backend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIventInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIventInfoForList) ProtoMessage() {}

func (x *UserIventInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIventInfoForList.ProtoReflect.Descriptor instead.
func (*UserIventInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{15}
}

func (x *UserIventInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserIventInfoForList) GetIventId() string {
	if x != nil {
		return x.IventId
	}
	return ""
}

func (x *UserIventInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserIventInfoForList) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *UserIventInfoForList) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type GetUserIventsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserIvents    []*GetUserIventInfoResponse `protobuf:"bytes,2,rep,name=user_ivents,json=userIvents,proto3" json:"user_ivents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIventsResponse) Reset() {
	*x = GetUserIventsResponse{}
	mi := &file_special_backend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIventsResponse) ProtoMessage() {}

func (x *GetUserIventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIventsResponse.ProtoReflect.Descriptor instead.
func (*GetUserIventsResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserIventsResponse) GetUserIvents() []*GetUserIventInfoResponse {
	if x != nil {
		return x.UserIvents
	}
	return nil
}

type GetItemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemInfoRequest) Reset() {
	*x = GetItemInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoRequest) ProtoMessage() {}

func (x *GetItemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetItemInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{17}
}

func (x *GetItemInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_special_backend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{18}
}

type GetItemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Pictures      []string               `protobuf:"bytes,5,rep,name=pictures,proto3" json:"pictures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemInfoResponse) Reset() {
	*x = GetItemInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoResponse) ProtoMessage() {}

func (x *GetItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{19}
}

func (x *GetItemInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetItemInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetItemInfoResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetItemInfoResponse) GetPictures() []string {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type ItemInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfoForList) Reset() {
	*x = ItemInfoForList{}
	mi := &file_special_backend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfoForList) ProtoMessage() {}

func (x *ItemInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfoForList.ProtoReflect.Descriptor instead.
func (*ItemInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{20}
}

func (x *ItemInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemInfoForList) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemInfoForList) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfoForList     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_special_backend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{21}
}

func (x *GetItemsResponse) GetItems() []*ItemInfoForList {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderItemInfoForCreatng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfoForCreatng) Reset() {
	*x = OrderItemInfoForCreatng{}
	mi := &file_special_backend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfoForCreatng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfoForCreatng) ProtoMessage() {}

func (x *OrderItemInfoForCreatng) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfoForCreatng.ProtoReflect.Descriptor instead.
func (*OrderItemInfoForCreatng) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{22}
}

func (x *OrderItemInfoForCreatng) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItemInfoForCreatng) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	CompletionDate *timestamppb.Timestamp     `protobuf:"bytes,1,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Comment        *string                    `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	Items          []*OrderItemInfoForCreatng `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_special_backend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{23}
}

func (x *CreateOrderRequest) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *CreateOrderRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItemInfoForCreatng {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoRequest) Reset() {
	*x = GetOrderInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoRequest) ProtoMessage() {}

func (x *GetOrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{24}
}

func (x *GetOrderInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_special_backend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{25}
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_special_backend_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderItemInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Picture       string                 `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfoForList) Reset() {
	*x = OrderItemInfoForList{}
	mi := &file_special_backend_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfoForList) ProtoMessage() {}

func (x *OrderItemInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfoForList.ProtoReflect.Descriptor instead.
func (*OrderItemInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{27}
}

func (x *OrderItemInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItemInfoForList) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItemInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrderItemInfoForList) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemInfoForList) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemInfoForList) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type GetOrderInfoResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Number         string                  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	FormDate       *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=form_date,json=formDate,proto3" json:"form_date,omitempty"`
	CompletionDate *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Comment        string                  `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Status         string                  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OrderAmount    int64                   `protobuf:"varint,6,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	Items          []*OrderItemInfoForList `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderInfoResponse) Reset() {
	*x = GetOrderInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoResponse) ProtoMessage() {}

func (x *GetOrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetOrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{28}
}

func (x *GetOrderInfoResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetOrderInfoResponse) GetFormDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FormDate
	}
	return nil
}

func (x *GetOrderInfoResponse) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *GetOrderInfoResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetOrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderInfoResponse) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *GetOrderInfoResponse) GetItems() []*OrderItemInfoForList {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderInfoForList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Number         string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OrderAmount    int64                  `protobuf:"varint,4,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfoForList) Reset() {
	*x = OrderInfoForList{}
	mi := &file_special_backend_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoForList) ProtoMessage() {}

func (x *OrderInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoForList.ProtoReflect.Descriptor instead.
func (*OrderInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{29}
}

func (x *OrderInfoForList) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderInfoForList) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *OrderInfoForList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoForList) GetOrderAmount() int64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfoForList    `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_special_backend_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{30}
}

func (x *GetOrdersResponse) GetOrders() []*OrderInfoForList {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_special_backend_proto protoreflect.FileDescriptor

const file_special_backend_proto_rawDesc = "" +
	"\n" +
	"\x15special-backend.proto\x12\x0especial_app_v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x13\n" +
	"\x11CreateUserRequest\"L\n" +
	"\x11UpdateUserRequest\x12&\n" +
	"\fphone_number\x18\x01 \x01(\tH\x00R\vphoneNumber\x88\x01\x01B\x0f\n" +
	"\r_phone_number\"\x10\n" +
	"\x0eGetUserRequest\"\x82\x01\n" +
	"\x13GetUserInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"%\n" +
	"\x13GetIventInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10GetIventsRequest\"\x90\x02\n" +
	"\x14GetIventInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x06 \x01(\x03R\n" +
	"totalSeats\x12%\n" +
	"\x0eoccupied_seats\x18\a \x01(\x03R\roccupiedSeats\x12\x1a\n" +
	"\bpictures\x18\b \x03(\tR\bpictures\"\xe8\x01\n" +
	"\x10IventInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x03R\n" +
	"totalSeats\x12%\n" +
	"\x0eoccupied_seats\x18\x06 \x01(\x03R\roccupiedSeats\x12\x18\n" +
	"\apicture\x18\a \x01(\tR\apicture\"M\n" +
	"\x11GetIventsResponse\x128\n" +
	"\x06ivents\x18\x01 \x03(\v2 .special_app_v1.IventInfoForListR\x06ivents\"]\n" +
	"\x16CreateUserIventRequest\x12\x19\n" +
	"\bivent_id\x18\x01 \x01(\tR\aiventId\x12(\n" +
	"\x10number_of_guests\x18\x02 \x01(\x03R\x0enumberOfGuests\")\n" +
	"\x17GetUserIventInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14GetUserIventsRequest\"R\n" +
	"\x16UpdateUserIventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10number_of_guests\x18\x02 \x01(\x03R\x0enumberOfGuests\"(\n" +
	"\x16DeleteUserIventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd7\x01\n" +
	"\x18GetUserIventInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bivent_id\x18\x02 \x01(\tR\aiventId\x12(\n" +
	"\x10number_of_guests\x18\x03 \x01(\tR\x0enumberOfGuests\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x18\n" +
	"\apicture\x18\x06 \x01(\tR\apicture\"\xa9\x01\n" +
	"\x14UserIventInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bivent_id\x18\x02 \x01(\tR\aiventId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x18\n" +
	"\apicture\x18\x05 \x01(\tR\apicture\"b\n" +
	"\x15GetUserIventsResponse\x12I\n" +
	"\vuser_ivents\x18\x02 \x03(\v2(.special_app_v1.GetUserIventInfoResponseR\n" +
	"userIvents\"$\n" +
	"\x12GetItemInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fGetItemsRequest\"\x8f\x01\n" +
	"\x13GetItemInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bpictures\x18\x05 \x03(\tR\bpictures\"g\n" +
	"\x0fItemInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\"I\n" +
	"\x10GetItemsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.special_app_v1.ItemInfoForListR\x05items\"N\n" +
	"\x17OrderItemInfoForCreatng\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\xc3\x01\n" +
	"\x12CreateOrderRequest\x12C\n" +
	"\x0fcompletion_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12=\n" +
	"\x05items\x18\x03 \x03(\v2'.special_app_v1.OrderItemInfoForCreatngR\x05itemsB\n" +
	"\n" +
	"\b_comment\"%\n" +
	"\x13GetOrderInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10GetOrdersRequest\"<\n" +
	"\x12UpdateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa1\x01\n" +
	"\x14OrderItemInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x18\n" +
	"\apicture\x18\x06 \x01(\tR\apicture\"\xbd\x02\n" +
	"\x14GetOrderInfoResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x127\n" +
	"\tform_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bformDate\x12C\n" +
	"\x0fcompletion_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\forder_amount\x18\x06 \x01(\x03R\vorderAmount\x12:\n" +
	"\x05items\x18\a \x03(\v2$.special_app_v1.OrderItemInfoForListR\x05items\"\xaa\x01\n" +
	"\x10OrderInfoForList\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12C\n" +
	"\x0fcompletion_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\forder_amount\x18\x04 \x01(\x03R\vorderAmount\"M\n" +
	"\x11GetOrdersResponse\x128\n" +
	"\x06orders\x18\x01 \x03(\v2 .special_app_v1.OrderInfoForListR\x06orders2\x91\x0e\n" +
	"\x11SpecialAppService\x12Z\n" +
	"\n" +
	"CreateUser\x12!.special_app_v1.CreateUserRequest\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v\"\t/v1/users\x12j\n" +
	"\n" +
	"UpdateUser\x12!.special_app_v1.UpdateUserRequest\x1a#.special_app_v1.GetUserInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*2\t/v1/users\x12a\n" +
	"\aGetUser\x12\x1e.special_app_v1.GetUserRequest\x1a#.special_app_v1.GetUserInfoResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12r\n" +
	"\fGetIventInfo\x12#.special_app_v1.GetIventInfoRequest\x1a$.special_app_v1.GetIventInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/ivents/{id}\x12d\n" +
	"\tGetIvents\x12 .special_app_v1.GetIventsRequest\x1a!.special_app_v1.GetIventsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/ivents\x12\x7f\n" +
	"\x0fCreateUserIvent\x12&.special_app_v1.CreateUserIventRequest\x1a(.special_app_v1.GetUserIventInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user_ivents\x12\x83\x01\n" +
	"\x10GetUserIventInfo\x12'.special_app_v1.GetUserIventInfoRequest\x1a(.special_app_v1.GetUserIventInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/user_ivents/{id}\x12u\n" +
	"\rGetUserIvents\x12$.special_app_v1.GetUserIventsRequest\x1a%.special_app_v1.GetUserIventsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/user_ivents\x12\x84\x01\n" +
	"\x0fUpdateUserIvent\x12&.special_app_v1.UpdateUserIventRequest\x1a(.special_app_v1.GetUserIventInfoResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/v1/user_ivents/{id}\x12o\n" +
	"\x0fDeleteUserIvent\x12&.special_app_v1.DeleteUserIventRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/user_ivents/{id}\x12n\n" +
	"\vGetItemInfo\x12\".special_app_v1.GetItemInfoRequest\x1a#.special_app_v1.GetItemInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/items/{id}\x12`\n" +
	"\bGetItems\x12\x1f.special_app_v1.GetItemsRequest\x1a .special_app_v1.GetItemsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/items\x12`\n" +
	"\vCreateOrder\x12\".special_app_v1.CreateOrderRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12r\n" +
	"\fGetOrderInfo\x12#.special_app_v1.GetOrderInfoRequest\x1a$.special_app_v1.GetOrderInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/orders/{id}\x12d\n" +
	"\tGetOrders\x12 .special_app_v1.GetOrdersRequest\x1a!.special_app_v1.GetOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12s\n" +
	"\vUpdateOrder\x12\".special_app_v1.UpdateOrderRequest\x1a$.special_app_v1.GetOrderInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/orders/{id}B)Z'special_app/pkg/proto/v1;special_app_v1b\x06proto3"

var (
	file_special_backend_proto_rawDescOnce sync.Once
	file_special_backend_proto_rawDescData []byte
)

func file_special_backend_proto_rawDescGZIP() []byte {
	file_special_backend_proto_rawDescOnce.Do(func() {
		file_special_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_special_backend_proto_rawDesc), len(file_special_backend_proto_rawDesc)))
	})
	return file_special_backend_proto_rawDescData
}

var file_special_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_special_backend_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: special_app_v1.CreateUserRequest
	(*UpdateUserRequest)(nil),        // 1: special_app_v1.UpdateUserRequest
	(*GetUserRequest)(nil),           // 2: special_app_v1.GetUserRequest
	(*GetUserInfoResponse)(nil),      // 3: special_app_v1.GetUserInfoResponse
	(*GetIventInfoRequest)(nil),      // 4: special_app_v1.GetIventInfoRequest
	(*GetIventsRequest)(nil),         // 5: special_app_v1.GetIventsRequest
	(*GetIventInfoResponse)(nil),     // 6: special_app_v1.GetIventInfoResponse
	(*IventInfoForList)(nil),         // 7: special_app_v1.IventInfoForList
	(*GetIventsResponse)(nil),        // 8: special_app_v1.GetIventsResponse
	(*CreateUserIventRequest)(nil),   // 9: special_app_v1.CreateUserIventRequest
	(*GetUserIventInfoRequest)(nil),  // 10: special_app_v1.GetUserIventInfoRequest
	(*GetUserIventsRequest)(nil),     // 11: special_app_v1.GetUserIventsRequest
	(*UpdateUserIventRequest)(nil),   // 12: special_app_v1.UpdateUserIventRequest
	(*DeleteUserIventRequest)(nil),   // 13: special_app_v1.DeleteUserIventRequest
	(*GetUserIventInfoResponse)(nil), // 14: special_app_v1.GetUserIventInfoResponse
	(*UserIventInfoForList)(nil),     // 15: special_app_v1.UserIventInfoForList
	(*GetUserIventsResponse)(nil),    // 16: special_app_v1.GetUserIventsResponse
	(*GetItemInfoRequest)(nil),       // 17: special_app_v1.GetItemInfoRequest
	(*GetItemsRequest)(nil),          // 18: special_app_v1.GetItemsRequest
	(*GetItemInfoResponse)(nil),      // 19: special_app_v1.GetItemInfoResponse
	(*ItemInfoForList)(nil),          // 20: special_app_v1.ItemInfoForList
	(*GetItemsResponse)(nil),         // 21: special_app_v1.GetItemsResponse
	(*OrderItemInfoForCreatng)(nil),  // 22: special_app_v1.OrderItemInfoForCreatng
	(*CreateOrderRequest)(nil),       // 23: special_app_v1.CreateOrderRequest
	(*GetOrderInfoRequest)(nil),      // 24: special_app_v1.GetOrderInfoRequest
	(*GetOrdersRequest)(nil),         // 25: special_app_v1.GetOrdersRequest
	(*UpdateOrderRequest)(nil),       // 26: special_app_v1.UpdateOrderRequest
	(*OrderItemInfoForList)(nil),     // 27: special_app_v1.OrderItemInfoForList
	(*GetOrderInfoResponse)(nil),     // 28: special_app_v1.GetOrderInfoResponse
	(*OrderInfoForList)(nil),         // 29: special_app_v1.OrderInfoForList
	(*GetOrdersResponse)(nil),        // 30: special_app_v1.GetOrdersResponse
	(*timestamppb.Timestamp)(nil),    // 31: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 32: google.protobuf.Empty
}
var file_special_backend_proto_depIdxs = []int32{
	31, // 0: special_app_v1.GetIventInfoResponse.datetime:type_name -> google.protobuf.Timestamp
	31, // 1: special_app_v1.IventInfoForList.datetime:type_name -> google.protobuf.Timestamp
	7,  // 2: special_app_v1.GetIventsResponse.ivents:type_name -> special_app_v1.IventInfoForList
	31, // 3: special_app_v1.GetUserIventInfoResponse.datetime:type_name -> google.protobuf.Timestamp
	31, // 4: special_app_v1.UserIventInfoForList.datetime:type_name -> google.protobuf.Timestamp
	14, // 5: special_app_v1.GetUserIventsResponse.user_ivents:type_name -> special_app_v1.GetUserIventInfoResponse
	20, // 6: special_app_v1.GetItemsResponse.items:type_name -> special_app_v1.ItemInfoForList
	31, // 7: special_app_v1.CreateOrderRequest.completion_date:type_name -> google.protobuf.Timestamp
	22, // 8: special_app_v1.CreateOrderRequest.items:type_name -> special_app_v1.OrderItemInfoForCreatng
	31, // 9: special_app_v1.GetOrderInfoResponse.form_date:type_name -> google.protobuf.Timestamp
	31, // 10: special_app_v1.GetOrderInfoResponse.completion_date:type_name -> google.protobuf.Timestamp
	27, // 11: special_app_v1.GetOrderInfoResponse.items:type_name -> special_app_v1.OrderItemInfoForList
	31, // 12: special_app_v1.OrderInfoForList.completion_date:type_name -> google.protobuf.Timestamp
	29, // 13: special_app_v1.GetOrdersResponse.orders:type_name -> special_app_v1.OrderInfoForList
	0,  // 14: special_app_v1.SpecialAppService.CreateUser:input_type -> special_app_v1.CreateUserRequest
	1,  // 15: special_app_v1.SpecialAppService.UpdateUser:input_type -> special_app_v1.UpdateUserRequest
	2,  // 16: special_app_v1.SpecialAppService.GetUser:input_type -> special_app_v1.GetUserRequest
	4,  // 17: special_app_v1.SpecialAppService.GetIventInfo:input_type -> special_app_v1.GetIventInfoRequest
	5,  // 18: special_app_v1.SpecialAppService.GetIvents:input_type -> special_app_v1.GetIventsRequest
	9,  // 19: special_app_v1.SpecialAppService.CreateUserIvent:input_type -> special_app_v1.CreateUserIventRequest
	10, // 20: special_app_v1.SpecialAppService.GetUserIventInfo:input_type -> special_app_v1.GetUserIventInfoRequest
	11, // 21: special_app_v1.SpecialAppService.GetUserIvents:input_type -> special_app_v1.GetUserIventsRequest
	12, // 22: special_app_v1.SpecialAppService.UpdateUserIvent:input_type -> special_app_v1.UpdateUserIventRequest
	13, // 23: special_app_v1.SpecialAppService.DeleteUserIvent:input_type -> special_app_v1.DeleteUserIventRequest
	17, // 24: special_app_v1.SpecialAppService.GetItemInfo:input_type -> special_app_v1.GetItemInfoRequest
	18, // 25: special_app_v1.SpecialAppService.GetItems:input_type -> special_app_v1.GetItemsRequest
	23, // 26: special_app_v1.SpecialAppService.CreateOrder:input_type -> special_app_v1.CreateOrderRequest
	24, // 27: special_app_v1.SpecialAppService.GetOrderInfo:input_type -> special_app_v1.GetOrderInfoRequest
	25, // 28: special_app_v1.SpecialAppService.GetOrders:input_type -> special_app_v1.GetOrdersRequest
	26, // 29: special_app_v1.SpecialAppService.UpdateOrder:input_type -> special_app_v1.UpdateOrderRequest
	32, // 30: special_app_v1.SpecialAppService.CreateUser:output_type -> google.protobuf.Empty
	3,  // 31: special_app_v1.SpecialAppService.UpdateUser:output_type -> special_app_v1.GetUserInfoResponse
	3,  // 32: special_app_v1.SpecialAppService.GetUser:output_type -> special_app_v1.GetUserInfoResponse
	6,  // 33: special_app_v1.SpecialAppService.GetIventInfo:output_type -> special_app_v1.GetIventInfoResponse
	8,  // 34: special_app_v1.SpecialAppService.GetIvents:output_type -> special_app_v1.GetIventsResponse
	14, // 35: special_app_v1.SpecialAppService.CreateUserIvent:output_type -> special_app_v1.GetUserIventInfoResponse
	14, // 36: special_app_v1.SpecialAppService.GetUserIventInfo:output_type -> special_app_v1.GetUserIventInfoResponse
	16, // 37: special_app_v1.SpecialAppService.GetUserIvents:output_type -> special_app_v1.GetUserIventsResponse
	14, // 38: special_app_v1.SpecialAppService.UpdateUserIvent:output_type -> special_app_v1.GetUserIventInfoResponse
	32, // 39: special_app_v1.SpecialAppService.DeleteUserIvent:output_type -> google.protobuf.Empty
	19, // 40: special_app_v1.SpecialAppService.GetItemInfo:output_type -> special_app_v1.GetItemInfoResponse
	21, // 41: special_app_v1.SpecialAppService.GetItems:output_type -> special_app_v1.GetItemsResponse
	32, // 42: special_app_v1.SpecialAppService.CreateOrder:output_type -> google.protobuf.Empty
	28, // 43: special_app_v1.SpecialAppService.GetOrderInfo:output_type -> special_app_v1.GetOrderInfoResponse
	30, // 44: special_app_v1.SpecialAppService.GetOrders:output_type -> special_app_v1.GetOrdersResponse
	28, // 45: special_app_v1.SpecialAppService.UpdateOrder:output_type -> special_app_v1.GetOrderInfoResponse
	30, // [30:46] is the sub-list for method output_type
	14, // [14:30] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_special_backend_proto_init() }
func file_special_backend_proto_init() {
	if File_special_backend_proto != nil {
		return
	}
	file_special_backend_proto_msgTypes[1].OneofWrappers = []any{}
	file_special_backend_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_special_backend_proto_rawDesc), len(file_special_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_special_backend_proto_goTypes,
		DependencyIndexes: file_special_backend_proto_depIdxs,
		MessageInfos:      file_special_backend_proto_msgTypes,
	}.Build()
	File_special_backend_proto = out.File
	file_special_backend_proto_goTypes = nil
	file_special_backend_proto_depIdxs = nil
}
