// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: special-backend.proto

package special_app_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PictureInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Picture       []byte                 `protobuf:"bytes,1,opt,name=picture,proto3" json:"picture,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PictureInfo) Reset() {
	*x = PictureInfo{}
	mi := &file_special_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PictureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureInfo) ProtoMessage() {}

func (x *PictureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureInfo.ProtoReflect.Descriptor instead.
func (*PictureInfo) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{0}
}

func (x *PictureInfo) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *PictureInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_special_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{1}
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   *string                `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_special_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_special_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{3}
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *GetUserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetEventInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventInfoRequest) Reset() {
	*x = GetEventInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventInfoRequest) ProtoMessage() {}

func (x *GetEventInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventInfoRequest.ProtoReflect.Descriptor instead.
func (*GetEventInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_special_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetEventsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetEventInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int32                  `protobuf:"varint,6,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats int32                  `protobuf:"varint,7,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	Pictures      []*PictureInfo         `protobuf:"bytes,8,rep,name=pictures,proto3" json:"pictures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventInfoResponse) Reset() {
	*x = GetEventInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventInfoResponse) ProtoMessage() {}

func (x *GetEventInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventInfoResponse.ProtoReflect.Descriptor instead.
func (*GetEventInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEventInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetEventInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetEventInfoResponse) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *GetEventInfoResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetEventInfoResponse) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *GetEventInfoResponse) GetOccupiedSeats() int32 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *GetEventInfoResponse) GetPictures() []*PictureInfo {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type EventInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	TotalSeats    int32                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	OccupiedSeats int32                  `protobuf:"varint,6,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	Picture       *PictureInfo           `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfoForList) Reset() {
	*x = EventInfoForList{}
	mi := &file_special_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfoForList) ProtoMessage() {}

func (x *EventInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfoForList.ProtoReflect.Descriptor instead.
func (*EventInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{8}
}

func (x *EventInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventInfoForList) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *EventInfoForList) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EventInfoForList) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *EventInfoForList) GetOccupiedSeats() int32 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *EventInfoForList) GetPicture() *PictureInfo {
	if x != nil {
		return x.Picture
	}
	return nil
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventInfoForList    `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_special_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsResponse) GetEvents() []*EventInfoForList {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetEventsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetEventsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type CreateUserEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NumberOfGuests int32                  `protobuf:"varint,2,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserEventRequest) Reset() {
	*x = CreateUserEventRequest{}
	mi := &file_special_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserEventRequest) ProtoMessage() {}

func (x *CreateUserEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserEventRequest.ProtoReflect.Descriptor instead.
func (*CreateUserEventRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateUserEventRequest) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type GetUserEventInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEventInfoRequest) Reset() {
	*x = GetUserEventInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEventInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEventInfoRequest) ProtoMessage() {}

func (x *GetUserEventInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEventInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserEventInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserEventInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEventsRequest) Reset() {
	*x = GetUserEventsRequest{}
	mi := &file_special_backend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEventsRequest) ProtoMessage() {}

func (x *GetUserEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEventsRequest.ProtoReflect.Descriptor instead.
func (*GetUserEventsRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserEventsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type UpdateUserEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumberOfGuests int32                  `protobuf:"varint,2,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserEventRequest) Reset() {
	*x = UpdateUserEventRequest{}
	mi := &file_special_backend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserEventRequest) ProtoMessage() {}

func (x *UpdateUserEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserEventRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserEventRequest) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

type DeleteUserEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserEventRequest) Reset() {
	*x = DeleteUserEventRequest{}
	mi := &file_special_backend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserEventRequest) ProtoMessage() {}

func (x *DeleteUserEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserEventRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserEventInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NumberOfGuests int32                  `protobuf:"varint,3,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Datetime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Picture        *PictureInfo           `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserEventInfoResponse) Reset() {
	*x = GetUserEventInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEventInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEventInfoResponse) ProtoMessage() {}

func (x *GetUserEventInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEventInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserEventInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserEventInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserEventInfoResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetUserEventInfoResponse) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

func (x *GetUserEventInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetUserEventInfoResponse) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *GetUserEventInfoResponse) GetPicture() *PictureInfo {
	if x != nil {
		return x.Picture
	}
	return nil
}

type UserEventInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Datetime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Picture       *PictureInfo           `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEventInfoForList) Reset() {
	*x = UserEventInfoForList{}
	mi := &file_special_backend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEventInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEventInfoForList) ProtoMessage() {}

func (x *UserEventInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEventInfoForList.ProtoReflect.Descriptor instead.
func (*UserEventInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{16}
}

func (x *UserEventInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserEventInfoForList) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserEventInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserEventInfoForList) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *UserEventInfoForList) GetPicture() *PictureInfo {
	if x != nil {
		return x.Picture
	}
	return nil
}

type GetUserEventsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserEvents    []*UserEventInfoForList `protobuf:"bytes,1,rep,name=user_events,json=userEvents,proto3" json:"user_events,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                   `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEventsResponse) Reset() {
	*x = GetUserEventsResponse{}
	mi := &file_special_backend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEventsResponse) ProtoMessage() {}

func (x *GetUserEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEventsResponse.ProtoReflect.Descriptor instead.
func (*GetUserEventsResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserEventsResponse) GetUserEvents() []*UserEventInfoForList {
	if x != nil {
		return x.UserEvents
	}
	return nil
}

func (x *GetUserEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserEventsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserEventsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetItemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemInfoRequest) Reset() {
	*x = GetItemInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoRequest) ProtoMessage() {}

func (x *GetItemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetItemInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{18}
}

func (x *GetItemInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_special_backend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{19}
}

func (x *GetItemsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetItemsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetItemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Pictures      []*PictureInfo         `protobuf:"bytes,5,rep,name=pictures,proto3" json:"pictures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemInfoResponse) Reset() {
	*x = GetItemInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemInfoResponse) ProtoMessage() {}

func (x *GetItemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetItemInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{20}
}

func (x *GetItemInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemInfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetItemInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetItemInfoResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetItemInfoResponse) GetPictures() []*PictureInfo {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type ItemInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Picture       *PictureInfo           `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfoForList) Reset() {
	*x = ItemInfoForList{}
	mi := &file_special_backend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfoForList) ProtoMessage() {}

func (x *ItemInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfoForList.ProtoReflect.Descriptor instead.
func (*ItemInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{21}
}

func (x *ItemInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemInfoForList) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemInfoForList) GetPicture() *PictureInfo {
	if x != nil {
		return x.Picture
	}
	return nil
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfoForList     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_special_backend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{22}
}

func (x *GetItemsResponse) GetItems() []*ItemInfoForList {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetItemsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetItemsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetItemsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type OrderItemInfoForCreatng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfoForCreatng) Reset() {
	*x = OrderItemInfoForCreatng{}
	mi := &file_special_backend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfoForCreatng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfoForCreatng) ProtoMessage() {}

func (x *OrderItemInfoForCreatng) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfoForCreatng.ProtoReflect.Descriptor instead.
func (*OrderItemInfoForCreatng) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{23}
}

func (x *OrderItemInfoForCreatng) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItemInfoForCreatng) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	CompletionDate *timestamppb.Timestamp     `protobuf:"bytes,1,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Comment        *string                    `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	OrderAmount    int32                      `protobuf:"varint,3,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	Items          []*OrderItemInfoForCreatng `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_special_backend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{24}
}

func (x *CreateOrderRequest) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *CreateOrderRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderAmount() int32 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*OrderItemInfoForCreatng {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderInfoRequest) Reset() {
	*x = GetOrderInfoRequest{}
	mi := &file_special_backend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoRequest) ProtoMessage() {}

func (x *GetOrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{25}
}

func (x *GetOrderInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_special_backend_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{26}
}

func (x *GetOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrdersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_special_backend_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderItemInfoForList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Picture       *PictureInfo           `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInfoForList) Reset() {
	*x = OrderItemInfoForList{}
	mi := &file_special_backend_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInfoForList) ProtoMessage() {}

func (x *OrderItemInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInfoForList.ProtoReflect.Descriptor instead.
func (*OrderItemInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{28}
}

func (x *OrderItemInfoForList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItemInfoForList) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItemInfoForList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrderItemInfoForList) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemInfoForList) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemInfoForList) GetPicture() *PictureInfo {
	if x != nil {
		return x.Picture
	}
	return nil
}

type GetOrderInfoResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Number         string                  `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	FormDate       *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=form_date,json=formDate,proto3" json:"form_date,omitempty"`
	CompletionDate *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Comment        string                  `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Status         string                  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OrderAmount    int32                   `protobuf:"varint,6,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	Items          []*OrderItemInfoForList `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderInfoResponse) Reset() {
	*x = GetOrderInfoResponse{}
	mi := &file_special_backend_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderInfoResponse) ProtoMessage() {}

func (x *GetOrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetOrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{29}
}

func (x *GetOrderInfoResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetOrderInfoResponse) GetFormDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FormDate
	}
	return nil
}

func (x *GetOrderInfoResponse) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *GetOrderInfoResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetOrderInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderInfoResponse) GetOrderAmount() int32 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *GetOrderInfoResponse) GetItems() []*OrderItemInfoForList {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderInfoForList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Number         string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	CompletionDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completion_date,json=completionDate,proto3" json:"completion_date,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OrderAmount    int32                  `protobuf:"varint,4,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderInfoForList) Reset() {
	*x = OrderInfoForList{}
	mi := &file_special_backend_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoForList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoForList) ProtoMessage() {}

func (x *OrderInfoForList) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoForList.ProtoReflect.Descriptor instead.
func (*OrderInfoForList) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{30}
}

func (x *OrderInfoForList) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderInfoForList) GetCompletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionDate
	}
	return nil
}

func (x *OrderInfoForList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderInfoForList) GetOrderAmount() int32 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfoForList    `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_special_backend_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_special_backend_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_special_backend_proto_rawDescGZIP(), []int{31}
}

func (x *GetOrdersResponse) GetOrders() []*OrderInfoForList {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrdersResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

var File_special_backend_proto protoreflect.FileDescriptor

const file_special_backend_proto_rawDesc = "" +
	"\n" +
	"\x15special-backend.proto\x12\x0especial_app_v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\vPictureInfo\x12\x18\n" +
	"\apicture\x18\x01 \x01(\fR\apicture\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\x13\n" +
	"\x11CreateUserRequest\"L\n" +
	"\x11UpdateUserRequest\x12&\n" +
	"\fphone_number\x18\x01 \x01(\tH\x00R\vphoneNumber\x88\x01\x01B\x0f\n" +
	"\r_phone_number\"\x10\n" +
	"\x0eGetUserRequest\"\x82\x01\n" +
	"\x13GetUserInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"%\n" +
	"\x13GetEventInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x10GetEventsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"\xad\x02\n" +
	"\x14GetEventInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x06 \x01(\x05R\n" +
	"totalSeats\x12%\n" +
	"\x0eoccupied_seats\x18\a \x01(\x05R\roccupiedSeats\x127\n" +
	"\bpictures\x18\b \x03(\v2\x1b.special_app_v1.PictureInfoR\bpictures\"\x85\x02\n" +
	"\x10EventInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x05R\n" +
	"totalSeats\x12%\n" +
	"\x0eoccupied_seats\x18\x06 \x01(\x05R\roccupiedSeats\x125\n" +
	"\apicture\x18\a \x01(\v2\x1b.special_app_v1.PictureInfoR\apicture\"\x92\x01\n" +
	"\x11GetEventsResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .special_app_v1.EventInfoForListR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"]\n" +
	"\x16CreateUserEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12(\n" +
	"\x10number_of_guests\x18\x02 \x01(\x05R\x0enumberOfGuests\")\n" +
	"\x17GetUserEventInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x14GetUserEventsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"R\n" +
	"\x16UpdateUserEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10number_of_guests\x18\x02 \x01(\x05R\x0enumberOfGuests\"(\n" +
	"\x16DeleteUserEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf4\x01\n" +
	"\x18GetUserEventInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12(\n" +
	"\x10number_of_guests\x18\x03 \x01(\x05R\x0enumberOfGuests\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x125\n" +
	"\apicture\x18\x06 \x01(\v2\x1b.special_app_v1.PictureInfoR\apicture\"\xc6\x01\n" +
	"\x14UserEventInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x126\n" +
	"\bdatetime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x125\n" +
	"\apicture\x18\x05 \x01(\v2\x1b.special_app_v1.PictureInfoR\apicture\"\xa3\x01\n" +
	"\x15GetUserEventsResponse\x12E\n" +
	"\vuser_events\x18\x01 \x03(\v2$.special_app_v1.UserEventInfoForListR\n" +
	"userEvents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"$\n" +
	"\x12GetItemInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x0fGetItemsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"\xac\x01\n" +
	"\x13GetItemInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x127\n" +
	"\bpictures\x18\x05 \x03(\v2\x1b.special_app_v1.PictureInfoR\bpictures\"\x84\x01\n" +
	"\x0fItemInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x125\n" +
	"\apicture\x18\x04 \x01(\v2\x1b.special_app_v1.PictureInfoR\apicture\"\x8e\x01\n" +
	"\x10GetItemsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.special_app_v1.ItemInfoForListR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"N\n" +
	"\x17OrderItemInfoForCreatng\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xe6\x01\n" +
	"\x12CreateOrderRequest\x12C\n" +
	"\x0fcompletion_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x1d\n" +
	"\acomment\x18\x02 \x01(\tH\x00R\acomment\x88\x01\x01\x12!\n" +
	"\forder_amount\x18\x03 \x01(\x05R\vorderAmount\x12=\n" +
	"\x05items\x18\x04 \x03(\v2'.special_app_v1.OrderItemInfoForCreatngR\x05itemsB\n" +
	"\n" +
	"\b_comment\"%\n" +
	"\x13GetOrderInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x10GetOrdersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"<\n" +
	"\x12UpdateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xbe\x01\n" +
	"\x14OrderItemInfoForList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x125\n" +
	"\apicture\x18\x06 \x01(\v2\x1b.special_app_v1.PictureInfoR\apicture\"\xbd\x02\n" +
	"\x14GetOrderInfoResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x127\n" +
	"\tform_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bformDate\x12C\n" +
	"\x0fcompletion_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\forder_amount\x18\x06 \x01(\x05R\vorderAmount\x12:\n" +
	"\x05items\x18\a \x03(\v2$.special_app_v1.OrderItemInfoForListR\x05items\"\xaa\x01\n" +
	"\x10OrderInfoForList\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12C\n" +
	"\x0fcompletion_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionDate\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\forder_amount\x18\x04 \x01(\x05R\vorderAmount\"\x92\x01\n" +
	"\x11GetOrdersResponse\x128\n" +
	"\x06orders\x18\x01 \x03(\v2 .special_app_v1.OrderInfoForListR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage2\xff\r\n" +
	"\x11SpecialAppService\x12Z\n" +
	"\n" +
	"CreateUser\x12!.special_app_v1.CreateUserRequest\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v\"\t/v1/users\x12j\n" +
	"\n" +
	"UpdateUser\x12!.special_app_v1.UpdateUserRequest\x1a#.special_app_v1.GetUserInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*2\t/v1/users\x12a\n" +
	"\aGetUser\x12\x1e.special_app_v1.GetUserRequest\x1a#.special_app_v1.GetUserInfoResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12r\n" +
	"\fGetEventInfo\x12#.special_app_v1.GetEventInfoRequest\x1a$.special_app_v1.GetEventInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/events/{id}\x12d\n" +
	"\tGetEvents\x12 .special_app_v1.GetEventsRequest\x1a!.special_app_v1.GetEventsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/events\x12m\n" +
	"\x0fCreateUserEvent\x12&.special_app_v1.CreateUserEventRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user_events\x12\x83\x01\n" +
	"\x10GetUserEventInfo\x12'.special_app_v1.GetUserEventInfoRequest\x1a(.special_app_v1.GetUserEventInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/user_events/{id}\x12u\n" +
	"\rGetUserEvents\x12$.special_app_v1.GetUserEventsRequest\x1a%.special_app_v1.GetUserEventsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/user_events\x12\x84\x01\n" +
	"\x0fUpdateUserEvent\x12&.special_app_v1.UpdateUserEventRequest\x1a(.special_app_v1.GetUserEventInfoResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/v1/user_events/{id}\x12o\n" +
	"\x0fDeleteUserEvent\x12&.special_app_v1.DeleteUserEventRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/user_events/{id}\x12n\n" +
	"\vGetItemInfo\x12\".special_app_v1.GetItemInfoRequest\x1a#.special_app_v1.GetItemInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/items/{id}\x12`\n" +
	"\bGetItems\x12\x1f.special_app_v1.GetItemsRequest\x1a .special_app_v1.GetItemsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/items\x12`\n" +
	"\vCreateOrder\x12\".special_app_v1.CreateOrderRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12r\n" +
	"\fGetOrderInfo\x12#.special_app_v1.GetOrderInfoRequest\x1a$.special_app_v1.GetOrderInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/orders/{id}\x12d\n" +
	"\tGetOrders\x12 .special_app_v1.GetOrdersRequest\x1a!.special_app_v1.GetOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12s\n" +
	"\vUpdateOrder\x12\".special_app_v1.UpdateOrderRequest\x1a$.special_app_v1.GetOrderInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/orders/{id}B)Z'special_app/pkg/proto/v1;special_app_v1b\x06proto3"

var (
	file_special_backend_proto_rawDescOnce sync.Once
	file_special_backend_proto_rawDescData []byte
)

func file_special_backend_proto_rawDescGZIP() []byte {
	file_special_backend_proto_rawDescOnce.Do(func() {
		file_special_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_special_backend_proto_rawDesc), len(file_special_backend_proto_rawDesc)))
	})
	return file_special_backend_proto_rawDescData
}

var file_special_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_special_backend_proto_goTypes = []any{
	(*PictureInfo)(nil),              // 0: special_app_v1.PictureInfo
	(*CreateUserRequest)(nil),        // 1: special_app_v1.CreateUserRequest
	(*UpdateUserRequest)(nil),        // 2: special_app_v1.UpdateUserRequest
	(*GetUserRequest)(nil),           // 3: special_app_v1.GetUserRequest
	(*GetUserInfoResponse)(nil),      // 4: special_app_v1.GetUserInfoResponse
	(*GetEventInfoRequest)(nil),      // 5: special_app_v1.GetEventInfoRequest
	(*GetEventsRequest)(nil),         // 6: special_app_v1.GetEventsRequest
	(*GetEventInfoResponse)(nil),     // 7: special_app_v1.GetEventInfoResponse
	(*EventInfoForList)(nil),         // 8: special_app_v1.EventInfoForList
	(*GetEventsResponse)(nil),        // 9: special_app_v1.GetEventsResponse
	(*CreateUserEventRequest)(nil),   // 10: special_app_v1.CreateUserEventRequest
	(*GetUserEventInfoRequest)(nil),  // 11: special_app_v1.GetUserEventInfoRequest
	(*GetUserEventsRequest)(nil),     // 12: special_app_v1.GetUserEventsRequest
	(*UpdateUserEventRequest)(nil),   // 13: special_app_v1.UpdateUserEventRequest
	(*DeleteUserEventRequest)(nil),   // 14: special_app_v1.DeleteUserEventRequest
	(*GetUserEventInfoResponse)(nil), // 15: special_app_v1.GetUserEventInfoResponse
	(*UserEventInfoForList)(nil),     // 16: special_app_v1.UserEventInfoForList
	(*GetUserEventsResponse)(nil),    // 17: special_app_v1.GetUserEventsResponse
	(*GetItemInfoRequest)(nil),       // 18: special_app_v1.GetItemInfoRequest
	(*GetItemsRequest)(nil),          // 19: special_app_v1.GetItemsRequest
	(*GetItemInfoResponse)(nil),      // 20: special_app_v1.GetItemInfoResponse
	(*ItemInfoForList)(nil),          // 21: special_app_v1.ItemInfoForList
	(*GetItemsResponse)(nil),         // 22: special_app_v1.GetItemsResponse
	(*OrderItemInfoForCreatng)(nil),  // 23: special_app_v1.OrderItemInfoForCreatng
	(*CreateOrderRequest)(nil),       // 24: special_app_v1.CreateOrderRequest
	(*GetOrderInfoRequest)(nil),      // 25: special_app_v1.GetOrderInfoRequest
	(*GetOrdersRequest)(nil),         // 26: special_app_v1.GetOrdersRequest
	(*UpdateOrderRequest)(nil),       // 27: special_app_v1.UpdateOrderRequest
	(*OrderItemInfoForList)(nil),     // 28: special_app_v1.OrderItemInfoForList
	(*GetOrderInfoResponse)(nil),     // 29: special_app_v1.GetOrderInfoResponse
	(*OrderInfoForList)(nil),         // 30: special_app_v1.OrderInfoForList
	(*GetOrdersResponse)(nil),        // 31: special_app_v1.GetOrdersResponse
	(*timestamppb.Timestamp)(nil),    // 32: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 33: google.protobuf.Empty
}
var file_special_backend_proto_depIdxs = []int32{
	32, // 0: special_app_v1.GetEventInfoResponse.datetime:type_name -> google.protobuf.Timestamp
	0,  // 1: special_app_v1.GetEventInfoResponse.pictures:type_name -> special_app_v1.PictureInfo
	32, // 2: special_app_v1.EventInfoForList.datetime:type_name -> google.protobuf.Timestamp
	0,  // 3: special_app_v1.EventInfoForList.picture:type_name -> special_app_v1.PictureInfo
	8,  // 4: special_app_v1.GetEventsResponse.events:type_name -> special_app_v1.EventInfoForList
	32, // 5: special_app_v1.GetUserEventInfoResponse.datetime:type_name -> google.protobuf.Timestamp
	0,  // 6: special_app_v1.GetUserEventInfoResponse.picture:type_name -> special_app_v1.PictureInfo
	32, // 7: special_app_v1.UserEventInfoForList.datetime:type_name -> google.protobuf.Timestamp
	0,  // 8: special_app_v1.UserEventInfoForList.picture:type_name -> special_app_v1.PictureInfo
	16, // 9: special_app_v1.GetUserEventsResponse.user_events:type_name -> special_app_v1.UserEventInfoForList
	0,  // 10: special_app_v1.GetItemInfoResponse.pictures:type_name -> special_app_v1.PictureInfo
	0,  // 11: special_app_v1.ItemInfoForList.picture:type_name -> special_app_v1.PictureInfo
	21, // 12: special_app_v1.GetItemsResponse.items:type_name -> special_app_v1.ItemInfoForList
	32, // 13: special_app_v1.CreateOrderRequest.completion_date:type_name -> google.protobuf.Timestamp
	23, // 14: special_app_v1.CreateOrderRequest.items:type_name -> special_app_v1.OrderItemInfoForCreatng
	0,  // 15: special_app_v1.OrderItemInfoForList.picture:type_name -> special_app_v1.PictureInfo
	32, // 16: special_app_v1.GetOrderInfoResponse.form_date:type_name -> google.protobuf.Timestamp
	32, // 17: special_app_v1.GetOrderInfoResponse.completion_date:type_name -> google.protobuf.Timestamp
	28, // 18: special_app_v1.GetOrderInfoResponse.items:type_name -> special_app_v1.OrderItemInfoForList
	32, // 19: special_app_v1.OrderInfoForList.completion_date:type_name -> google.protobuf.Timestamp
	30, // 20: special_app_v1.GetOrdersResponse.orders:type_name -> special_app_v1.OrderInfoForList
	1,  // 21: special_app_v1.SpecialAppService.CreateUser:input_type -> special_app_v1.CreateUserRequest
	2,  // 22: special_app_v1.SpecialAppService.UpdateUser:input_type -> special_app_v1.UpdateUserRequest
	3,  // 23: special_app_v1.SpecialAppService.GetUser:input_type -> special_app_v1.GetUserRequest
	5,  // 24: special_app_v1.SpecialAppService.GetEventInfo:input_type -> special_app_v1.GetEventInfoRequest
	6,  // 25: special_app_v1.SpecialAppService.GetEvents:input_type -> special_app_v1.GetEventsRequest
	10, // 26: special_app_v1.SpecialAppService.CreateUserEvent:input_type -> special_app_v1.CreateUserEventRequest
	11, // 27: special_app_v1.SpecialAppService.GetUserEventInfo:input_type -> special_app_v1.GetUserEventInfoRequest
	12, // 28: special_app_v1.SpecialAppService.GetUserEvents:input_type -> special_app_v1.GetUserEventsRequest
	13, // 29: special_app_v1.SpecialAppService.UpdateUserEvent:input_type -> special_app_v1.UpdateUserEventRequest
	14, // 30: special_app_v1.SpecialAppService.DeleteUserEvent:input_type -> special_app_v1.DeleteUserEventRequest
	18, // 31: special_app_v1.SpecialAppService.GetItemInfo:input_type -> special_app_v1.GetItemInfoRequest
	19, // 32: special_app_v1.SpecialAppService.GetItems:input_type -> special_app_v1.GetItemsRequest
	24, // 33: special_app_v1.SpecialAppService.CreateOrder:input_type -> special_app_v1.CreateOrderRequest
	25, // 34: special_app_v1.SpecialAppService.GetOrderInfo:input_type -> special_app_v1.GetOrderInfoRequest
	26, // 35: special_app_v1.SpecialAppService.GetOrders:input_type -> special_app_v1.GetOrdersRequest
	27, // 36: special_app_v1.SpecialAppService.UpdateOrder:input_type -> special_app_v1.UpdateOrderRequest
	33, // 37: special_app_v1.SpecialAppService.CreateUser:output_type -> google.protobuf.Empty
	4,  // 38: special_app_v1.SpecialAppService.UpdateUser:output_type -> special_app_v1.GetUserInfoResponse
	4,  // 39: special_app_v1.SpecialAppService.GetUser:output_type -> special_app_v1.GetUserInfoResponse
	7,  // 40: special_app_v1.SpecialAppService.GetEventInfo:output_type -> special_app_v1.GetEventInfoResponse
	9,  // 41: special_app_v1.SpecialAppService.GetEvents:output_type -> special_app_v1.GetEventsResponse
	33, // 42: special_app_v1.SpecialAppService.CreateUserEvent:output_type -> google.protobuf.Empty
	15, // 43: special_app_v1.SpecialAppService.GetUserEventInfo:output_type -> special_app_v1.GetUserEventInfoResponse
	17, // 44: special_app_v1.SpecialAppService.GetUserEvents:output_type -> special_app_v1.GetUserEventsResponse
	15, // 45: special_app_v1.SpecialAppService.UpdateUserEvent:output_type -> special_app_v1.GetUserEventInfoResponse
	33, // 46: special_app_v1.SpecialAppService.DeleteUserEvent:output_type -> google.protobuf.Empty
	20, // 47: special_app_v1.SpecialAppService.GetItemInfo:output_type -> special_app_v1.GetItemInfoResponse
	22, // 48: special_app_v1.SpecialAppService.GetItems:output_type -> special_app_v1.GetItemsResponse
	33, // 49: special_app_v1.SpecialAppService.CreateOrder:output_type -> google.protobuf.Empty
	29, // 50: special_app_v1.SpecialAppService.GetOrderInfo:output_type -> special_app_v1.GetOrderInfoResponse
	31, // 51: special_app_v1.SpecialAppService.GetOrders:output_type -> special_app_v1.GetOrdersResponse
	29, // 52: special_app_v1.SpecialAppService.UpdateOrder:output_type -> special_app_v1.GetOrderInfoResponse
	37, // [37:53] is the sub-list for method output_type
	21, // [21:37] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_special_backend_proto_init() }
func file_special_backend_proto_init() {
	if File_special_backend_proto != nil {
		return
	}
	file_special_backend_proto_msgTypes[2].OneofWrappers = []any{}
	file_special_backend_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_special_backend_proto_rawDesc), len(file_special_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_special_backend_proto_goTypes,
		DependencyIndexes: file_special_backend_proto_depIdxs,
		MessageInfos:      file_special_backend_proto_msgTypes,
	}.Build()
	File_special_backend_proto = out.File
	file_special_backend_proto_goTypes = nil
	file_special_backend_proto_depIdxs = nil
}
