// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: special-backend.proto

package special_app_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpecialAppService_CreateUser_FullMethodName       = "/special_app_v1.SpecialAppService/CreateUser"
	SpecialAppService_UpdateUser_FullMethodName       = "/special_app_v1.SpecialAppService/UpdateUser"
	SpecialAppService_GetUser_FullMethodName          = "/special_app_v1.SpecialAppService/GetUser"
	SpecialAppService_GetEventInfo_FullMethodName     = "/special_app_v1.SpecialAppService/GetEventInfo"
	SpecialAppService_GetEvents_FullMethodName        = "/special_app_v1.SpecialAppService/GetEvents"
	SpecialAppService_CreateUserEvent_FullMethodName  = "/special_app_v1.SpecialAppService/CreateUserEvent"
	SpecialAppService_GetUserEventInfo_FullMethodName = "/special_app_v1.SpecialAppService/GetUserEventInfo"
	SpecialAppService_GetUserEvents_FullMethodName    = "/special_app_v1.SpecialAppService/GetUserEvents"
	SpecialAppService_UpdateUserEvent_FullMethodName  = "/special_app_v1.SpecialAppService/UpdateUserEvent"
	SpecialAppService_DeleteUserEvent_FullMethodName  = "/special_app_v1.SpecialAppService/DeleteUserEvent"
	SpecialAppService_GetItemInfo_FullMethodName      = "/special_app_v1.SpecialAppService/GetItemInfo"
	SpecialAppService_GetItems_FullMethodName         = "/special_app_v1.SpecialAppService/GetItems"
	SpecialAppService_CreateOrder_FullMethodName      = "/special_app_v1.SpecialAppService/CreateOrder"
	SpecialAppService_GetOrderInfo_FullMethodName     = "/special_app_v1.SpecialAppService/GetOrderInfo"
	SpecialAppService_GetOrders_FullMethodName        = "/special_app_v1.SpecialAppService/GetOrders"
	SpecialAppService_UpdateOrder_FullMethodName      = "/special_app_v1.SpecialAppService/UpdateOrder"
)

// SpecialAppServiceClient is the client API for SpecialAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpecialAppServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	GetEventInfo(ctx context.Context, in *GetEventInfoRequest, opts ...grpc.CallOption) (*GetEventInfoResponse, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	CreateUserEvent(ctx context.Context, in *CreateUserEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserEventInfo(ctx context.Context, in *GetUserEventInfoRequest, opts ...grpc.CallOption) (*GetUserEventInfoResponse, error)
	GetUserEvents(ctx context.Context, in *GetUserEventsRequest, opts ...grpc.CallOption) (*GetUserEventsResponse, error)
	UpdateUserEvent(ctx context.Context, in *UpdateUserEventRequest, opts ...grpc.CallOption) (*GetUserEventInfoResponse, error)
	DeleteUserEvent(ctx context.Context, in *DeleteUserEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetItemInfo(ctx context.Context, in *GetItemInfoRequest, opts ...grpc.CallOption) (*GetItemInfoResponse, error)
	GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetOrderInfo(ctx context.Context, in *GetOrderInfoRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error)
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error)
}

type specialAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecialAppServiceClient(cc grpc.ClientConnInterface) SpecialAppServiceClient {
	return &specialAppServiceClient{cc}
}

func (c *specialAppServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SpecialAppService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetEventInfo(ctx context.Context, in *GetEventInfoRequest, opts ...grpc.CallOption) (*GetEventInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetEventInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) CreateUserEvent(ctx context.Context, in *CreateUserEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SpecialAppService_CreateUserEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetUserEventInfo(ctx context.Context, in *GetUserEventInfoRequest, opts ...grpc.CallOption) (*GetUserEventInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserEventInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetUserEventInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetUserEvents(ctx context.Context, in *GetUserEventsRequest, opts ...grpc.CallOption) (*GetUserEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserEventsResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetUserEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) UpdateUserEvent(ctx context.Context, in *UpdateUserEventRequest, opts ...grpc.CallOption) (*GetUserEventInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserEventInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_UpdateUserEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) DeleteUserEvent(ctx context.Context, in *DeleteUserEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SpecialAppService_DeleteUserEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetItemInfo(ctx context.Context, in *GetItemInfoRequest, opts ...grpc.CallOption) (*GetItemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetItemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*GetItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemsResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SpecialAppService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetOrderInfo(ctx context.Context, in *GetOrderInfoRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetOrderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_GetOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialAppServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*GetOrderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderInfoResponse)
	err := c.cc.Invoke(ctx, SpecialAppService_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecialAppServiceServer is the server API for SpecialAppService service.
// All implementations must embed UnimplementedSpecialAppServiceServer
// for forward compatibility.
type SpecialAppServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*emptypb.Empty, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*GetUserInfoResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserInfoResponse, error)
	GetEventInfo(context.Context, *GetEventInfoRequest) (*GetEventInfoResponse, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	CreateUserEvent(context.Context, *CreateUserEventRequest) (*emptypb.Empty, error)
	GetUserEventInfo(context.Context, *GetUserEventInfoRequest) (*GetUserEventInfoResponse, error)
	GetUserEvents(context.Context, *GetUserEventsRequest) (*GetUserEventsResponse, error)
	UpdateUserEvent(context.Context, *UpdateUserEventRequest) (*GetUserEventInfoResponse, error)
	DeleteUserEvent(context.Context, *DeleteUserEventRequest) (*emptypb.Empty, error)
	GetItemInfo(context.Context, *GetItemInfoRequest) (*GetItemInfoResponse, error)
	GetItems(context.Context, *GetItemsRequest) (*GetItemsResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*emptypb.Empty, error)
	GetOrderInfo(context.Context, *GetOrderInfoRequest) (*GetOrderInfoResponse, error)
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
	UpdateOrder(context.Context, *UpdateOrderRequest) (*GetOrderInfoResponse, error)
	mustEmbedUnimplementedSpecialAppServiceServer()
}

// UnimplementedSpecialAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecialAppServiceServer struct{}

func (UnimplementedSpecialAppServiceServer) CreateUser(context.Context, *CreateUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSpecialAppServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetEventInfo(context.Context, *GetEventInfoRequest) (*GetEventInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventInfo not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedSpecialAppServiceServer) CreateUserEvent(context.Context, *CreateUserEventRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserEvent not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetUserEventInfo(context.Context, *GetUserEventInfoRequest) (*GetUserEventInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEventInfo not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetUserEvents(context.Context, *GetUserEventsRequest) (*GetUserEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEvents not implemented")
}
func (UnimplementedSpecialAppServiceServer) UpdateUserEvent(context.Context, *UpdateUserEventRequest) (*GetUserEventInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserEvent not implemented")
}
func (UnimplementedSpecialAppServiceServer) DeleteUserEvent(context.Context, *DeleteUserEventRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserEvent not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetItemInfo(context.Context, *GetItemInfoRequest) (*GetItemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemInfo not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetItems(context.Context, *GetItemsRequest) (*GetItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedSpecialAppServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetOrderInfo(context.Context, *GetOrderInfoRequest) (*GetOrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}
func (UnimplementedSpecialAppServiceServer) GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (UnimplementedSpecialAppServiceServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*GetOrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedSpecialAppServiceServer) mustEmbedUnimplementedSpecialAppServiceServer() {}
func (UnimplementedSpecialAppServiceServer) testEmbeddedByValue()                           {}

// UnsafeSpecialAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecialAppServiceServer will
// result in compilation errors.
type UnsafeSpecialAppServiceServer interface {
	mustEmbedUnimplementedSpecialAppServiceServer()
}

func RegisterSpecialAppServiceServer(s grpc.ServiceRegistrar, srv SpecialAppServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpecialAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecialAppService_ServiceDesc, srv)
}

func _SpecialAppService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetEventInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetEventInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetEventInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetEventInfo(ctx, req.(*GetEventInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_CreateUserEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).CreateUserEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_CreateUserEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).CreateUserEvent(ctx, req.(*CreateUserEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetUserEventInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEventInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetUserEventInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetUserEventInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetUserEventInfo(ctx, req.(*GetUserEventInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetUserEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetUserEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetUserEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetUserEvents(ctx, req.(*GetUserEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_UpdateUserEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).UpdateUserEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_UpdateUserEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).UpdateUserEvent(ctx, req.(*UpdateUserEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_DeleteUserEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).DeleteUserEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_DeleteUserEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).DeleteUserEvent(ctx, req.(*DeleteUserEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetItemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetItemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetItemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetItemInfo(ctx, req.(*GetItemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetItems(ctx, req.(*GetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetOrderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetOrderInfo(ctx, req.(*GetOrderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_GetOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialAppService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialAppServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialAppService_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialAppServiceServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpecialAppService_ServiceDesc is the grpc.ServiceDesc for SpecialAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecialAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "special_app_v1.SpecialAppService",
	HandlerType: (*SpecialAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SpecialAppService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _SpecialAppService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _SpecialAppService_GetUser_Handler,
		},
		{
			MethodName: "GetEventInfo",
			Handler:    _SpecialAppService_GetEventInfo_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _SpecialAppService_GetEvents_Handler,
		},
		{
			MethodName: "CreateUserEvent",
			Handler:    _SpecialAppService_CreateUserEvent_Handler,
		},
		{
			MethodName: "GetUserEventInfo",
			Handler:    _SpecialAppService_GetUserEventInfo_Handler,
		},
		{
			MethodName: "GetUserEvents",
			Handler:    _SpecialAppService_GetUserEvents_Handler,
		},
		{
			MethodName: "UpdateUserEvent",
			Handler:    _SpecialAppService_UpdateUserEvent_Handler,
		},
		{
			MethodName: "DeleteUserEvent",
			Handler:    _SpecialAppService_DeleteUserEvent_Handler,
		},
		{
			MethodName: "GetItemInfo",
			Handler:    _SpecialAppService_GetItemInfo_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _SpecialAppService_GetItems_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _SpecialAppService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrderInfo",
			Handler:    _SpecialAppService_GetOrderInfo_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _SpecialAppService_GetOrders_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _SpecialAppService_UpdateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "special-backend.proto",
}
